[theme]
primaryColor = "#2A9D8F"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#E3F2FD"
textColor = "#2D3748"
font = "sans serif"

[server]
maxUploadSize = 15

[client]
showErrorDetails = false
